### PR TITLE
Added code to support PayPal only payments

### PR DESCRIPTION
**Pull request by lewisbarber**
I've added an implementation for the PayPal payment popup in the same single file as used already.

Let me know if you would prefer this to be split out into a separate file, thanks!

### CODE REVIEW

**Comment by alanhhwong** [comment]
Thanks for the PR @lewisbarber, just two questions:
1) bundleId isn't used in the iOS code?  We can't hardcode the returnURLScheme
2) we might want to allow setting of bundleId elsewhere since it's only used for PayPal/Venmo One Touch.  Could be a separate function, or part of the showPayPalViewController function?  Just don't want to complicate things for those who only need the basics (v.zero) for accepting payments

Makes sense?

**Comment by lewisbarber** [comment]
Hey, thanks for getting back to me, will make some updates to incorporate your comments then commit shortly. I think I've already changed the way the bundleId works locally on my machine, and I pass it into the 'setup' method in the JS file, so I'll push this up too.

**Comment by lewisbarber** [comment]
I've added a method called setupWithBundleId and left your setup method as it was before. Also updated the JS to pass the required values to iOS code. Let me know if any other updates are required? Thanks

**Comment by alanhhwong** [comment]
Looks good @lewisbarber thanks!

**Pull request merged**
